### ISSUE TITLE
Ruby 2.3.1 released

### ISSUE THREAD

**Issue by deivid-rodriguez** [brightbox/deb-ruby2.3#1]
Not sure this is the right place to ask for this, but...

Can we get in in Brightbox? Thanks!

**Comment by johnl** [comment]
Currently building: https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng-experimental/+builds?build_state=building

**Comment by johnl** [comment]
done. copied over!

**Comment by deivid-rodriguez** [comment]
Thanks! I'll try this soon.
